import express from "express";
import ProjectRoutes from "./routes/ProjectRoutes.js";
import bodyParser from "body-parser";
import cors from "cors";
const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cors());
app.use("/projects", ProjectRoutes);
export default app;
