name: Build and Deploy Backend Docker Image to AKS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      AKS_CLUSTER: <aks-cluster-name>
      RESOURCE_GROUP: vishal-ai
      IMAGE_NAME: mcaupyshop-backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    
    - name: Build Docker image
      run: |
        docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest ./backend/.
    - name: Push Docker image to Docker Hub
      run: |
        docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
      
